### ISSUE TITLE
Autosaving drafts

### ISSUE THREAD

**Issue by konaya** [litlifesoftware/HistoryOfMe#3]
# Problem

When typing up an entry and then tabbing out, sometimes the entry is lost, and an empty entry named Untitled has been saved.

# Suggestion

Implement a Draft status for entries, and have entries be auto-saved every couple of words as such.

**Comment by eightgran** [comment]
Thank you for feedback, konaya! 

I agree. Autosaving should actually be a must-have to prevent losing data. I will look into that!

Regards, Michael

**Comment by eightgran** [comment]
Hey konaya,
thank you for your suggestion. Diary entries are now auto-saved every 60 seconds since [v1.3.0+5](https://github.com/litlifesoftware/HistoryOfMe/releases/tag/v1.3.0%2B5)
Regards, Michael
